{% set name = "dictdatabase" %}
{% set version = "2.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dictdatabase-{{ version }}.tar.gz
  sha256: a1daefa96149792c79ccc94bc5b96115544ec5547e811e79e934f9245a12ab77

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core
    - python >=3.8,<4.0
  run:
    - python >=3.8,<4.0
    - orjson >=3.8.5,<4.0.0

test:
  imports:
    - dictdatabase
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mkrd/DictDataBase
  summary: Easy-to-use database using dicts
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
