{% set name = "dictdatabase" %}
{% set version = "2.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dictdatabase-{{ version }}.tar.gz
  sha256: 0b14780bf56723e4a0a85ec098c045c31b2c2fd86ed08033ecab9925724d14eb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - poetry-core
    - python {{ python_min }}
  run:
    - python >={{ python_min }},<4.0.0
    - orjson >=3.8.7,<4.0.0

test:
  imports:
    - dictdatabase
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/mkrd/DictDataBase
  summary: Easy-to-use database using dicts
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
